In [130]:
import numpy as np

In [ ]:
a=np.array([1,2,3],dtype='int8')
print(a)

[1 2 3]


In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

1

Get size

In [ ]:
a.size

3

Get total size

In [ ]:
a.size * a.itemsize

3

In [10]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

Get a specific element

In [ ]:
a[1,5]

13

In [ ]:
# get specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# get specific column
a[:,2]

array([ 3, 10])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
#replace the value
a[1,5]=20

In [ ]:
a[1]

array([ 8,  9, 10, 11, 12, 20, 14])

In [ ]:
#replace value to colum
a[:,2]=[1,2]

In [ ]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [ ]:
#3 D Example

In [ ]:
c=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]],
            [[9,10],[11,12]],
            [[13,14],[]]])

In [ ]:
c[0][1][1]

4

In [ ]:
c[:,0,:]

array([[1, 2],
       [5, 6]])

In [4]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [8]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [14]:
#ANy other number (full)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
np.full(a.shape,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [24]:
np.full(a.shape,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [ ]:
np.ones((23,2))

In [27]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
output=np.zeros((5,5))
output

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
z=np.ones((3,3))
z[1,1]=0
z

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [68]:
output[1:4,1:4]=z
output[1:4,4]=[0,0,0]
output
# output[0:2,0:2]=[[1,1],[1,1]]
# output[0:2,3:5]=[[1,1],[1,1]]
# output[3:5,3:5]=[[1,1],[1,1]]
# output[3:5,0:2]=[[1,1],[1,1]]
output[:,0:2]=[[1,1],[1,1],[1,1],[1,1],[1,1]]
output[:,3:5]=[[1,1],[1,1],[1,1],[1,1],[1,1]]
output[4,2]=1
output[0,2]=1
nine=np.full((5,5),9)
nine
eight=np.full((3,3),8)
eight
eight[1,1]=7
nine[1:4,1:4]=eight
nine

array([[9, 9, 9, 9, 9],
       [9, 8, 8, 8, 9],
       [9, 8, 7, 8, 9],
       [9, 8, 8, 8, 9],
       [9, 9, 9, 9, 9]])

In [17]:
np.random.rand(4,2,3
               )

array([[[0.88236015, 0.36144238, 0.2741974 ],
        [0.26438004, 0.72181861, 0.02090704]],

       [[0.05024224, 0.03185176, 0.07462186],
        [0.13982299, 0.54368954, 0.59745467]],

       [[0.14546842, 0.18479392, 0.35998594],
        [0.81990213, 0.33096386, 0.87027592]],

       [[0.99939446, 0.22566282, 0.68936434],
        [0.65417493, 0.17880111, 0.8950978 ]]])

In [19]:
np.random.random_sample(a.shape)

array([[0.88994892, 0.56268289, 0.92480891, 0.68177626, 0.88231905,
        0.71390377, 0.85792858],
       [0.49401503, 0.46307223, 0.15320039, 0.73280424, 0.02908927,
        0.65964474, 0.15202112]])

In [22]:
np.random.randint(7,size=(3,3))

array([[2, 6, 6],
       [3, 2, 5],
       [2, 6, 1]])

In [69]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
#Repeat a array
arr=np.array([[1,2,3],[4,5,6]])
r1=np.repeat(arr,3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [85]:
a=np.array([1,2,3])
b=a.copy()
b[0]

1

In [86]:
a+2

array([3, 4, 5])

In [87]:
a*2

array([2, 4, 6])

In [88]:
a/2

array([0.5, 1. , 1.5])

In [89]:
a/2

array([0.5, 1. , 1.5])

In [90]:
a+b

array([2, 4, 6])

In [92]:
a **2

array([1, 4, 9])

In [93]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [95]:
d=np.identity(3)

In [97]:
#Find the determinant
np.linalg.det(d)

1.0

Stats

In [98]:
Stats=np.array([[1,2,3],[4,5,6]])

In [99]:
#Min valu in Rows
np.min(Stats, axis=0)

array([1, 2, 3])

In [111]:

np.max(Stats, axis=0)

array([4, 5, 6])

In [110]:
np.min(Stats,axis=1)

array([1, 4])

In [107]:
np.max(Stats,axis=1)

array([3, 6])

In [112]:
#over max min
np.max(Stats)

6

In [113]:
np.min(Stats)

1

In [117]:
# Change shape

before=np.array([[1,2,3,4],[5,6,7,8]])

after=before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [126]:
#Horizontal Stack

e=np.ones((2,4))
f=np.zeros((2,4))

print(e)
print("f")
print(f)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
f
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [125]:
#horizontal stack
np.hstack([e,f,e,f])

array([[1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.]])

In [127]:
#vertical Stack
np.vstack((e,f,e,f))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
r=np.array([[1,2,3,4],
           [6,7,8,9]])
t=np.array([[10,11,12,13],
           [14,15,16,17]])

m=np.min(r,axis=0)
print(m)
n=np.max(r,axis=0)
print(n)

[1 2 3 4]
[6 7 8 9]


In [141]:
np.max(r,axis=1)

array([4, 9])

In [142]:
#cross number in array
r[[0,1],[2,3]]

array([3, 9])